apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
#resources:
patchesJson6902:
- target:
    kind: ConfigMap
    version: v1
    name: nifi-parameters
  path: parameters-cm.yaml
- target:
    kind: StatefulSet
    group: apps
    version: v1
    name: nifi
  path: nifi-ss.yaml

