---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: route-create-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: route-create-role
subjects:
  - kind: ServiceAccount
    name: nifi-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: route-create-role
rules:
  - verbs:
      - get
      - create
    apiGroups:
      - ''
      - route.openshift.io
    resources:
      - routes
  - verbs:
      - create
    apiGroups:
      - ''
      - route.openshift.io
    resources:
      - routes/custom-host
