---
varReference:
  - path: spec/template/spec/containers/command
    kind: Deployment
  - path: data/authorizers.xml
    kind: ConfigMap
  - path: data/login-identity-providers.xml
    kind: ConfigMap
  - path: data/flow.xml
    kind: ConfigMap
  - path: data/nifi.properties
    kind: ConfigMap

