---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nifi-ca
spec:
  accessModes:
    - "ReadWriteOnce"
  storageClassName: {{ .Values.storageClass }}
  resources:
    requests:
      storage: 1Gi
