---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: nifi
  namespace: mberghold-dev
  labels:
    app: nifi
    component.opendatahub.io/name: nifi
    opendatahub.io/component: 'true'
spec:
  to:
    kind: Service
    name: nifi
  tls: null
  host: nifi-mberghold-dev.apps.sandbox-m3.1530.p1.openshiftapps.com
  path: /nifi
  port:
    targetPort: https