---
apiVersion: v1
kind: Service
metadata:
  name: nifi-headless
  labels:
    app: "nifi"
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 8443
      name: http
      targetPort: 8443
  selector:
    app: "nifi"
