apiVersion: v2
name: helm-nifi
description: A Helm chart for deploying Nifi in Openshift.

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# Chart version, starting at 1.0.0 and increasing to follow Semantic Versioning (https://semver.org/)
version: 1.0.0

# The appVersion refers to the version of Nifi that is being deployed with our image.
appVersion: 1.25.0

dependencies:
  - name: ca
    version: ^1.0.1
    condition: ca.enabled
  - name: zookeeper
    version: ^9.2.7
    condition: zookeeper.enabled